import io
from flask import Flask, render_template, request, send_file
from fpdf import FPDF
from core.preprocessor import extract_text_from_file
from core.plagiarism import PlagiarismDetector
from core.ai_detector import AIOstDetector

app = Flask(__name__)
plag_detector = PlagiarismDetector()
ai_detector = AIOstDetector()

@app.route("/", methods=["GET", "POST"])
def plagiarism():
    if request.method == "POST":
        doc1_text = request.form.get("text1", "")
        doc2_text = request.form.get("text2", "")

        file1 = request.files.get("file1")
        file2 = request.files.get("file2")

        if file1 and file1.filename:
            doc1_text = extract_text_from_file(file1)
        if file2 and file2.filename:
            doc2_text = extract_text_from_file(file2)

        results = plag_detector.detect_plagiarism(doc1_text, doc2_text)
        stats = plag_detector.get_word_stats(doc1_text, doc2_text)
        
        return render_template("plagiarism.html", plag_results=results, stats=stats, doc1=doc1_text, doc2=doc2_text)
    
    return render_template("plagiarism.html")

@app.route("/ai", methods=["GET", "POST"])
def ai_detection():
    if request.method == "POST":
        doc1_text = request.form.get("text1", "")
        file1 = request.files.get("file1")

        if file1 and file1.filename:
            doc1_text = extract_text_from_file(file1)

        ai_res = ai_detector.detect(doc1_text)
        return render_template("ai.html", ai_results=ai_res, doc1=doc1_text)

    return render_template("ai.html")

@app.route("/download_report", methods=["POST"])
def download_report():
    score = request.form.get("score", "N/A")
    level = request.form.get("level", "N/A")
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=15)
    pdf.cell(200, 10, txt="PLAGIARISM AND AI CONTENT REPORT", ln=1, align='C')
    
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Similarity Score: {score}%", ln=1)
    pdf.cell(200, 10, txt=f"Plagiarism Level: {level}", ln=1)
    
    pdf.cell(200, 10, txt="Detailed Report generated by NLP Python Project.", ln=1)
    
    pdf_buffer = io.BytesIO()
    pdf_out = pdf.output(dest="S")
    pdf_bytes = pdf_out.encode("latin-1") if isinstance(pdf_out, str) else bytes(pdf_out)
    pdf_buffer.write(pdf_bytes)
    pdf_buffer.seek(0)
    
    return send_file(pdf_buffer, as_attachment=True, download_name="plagiarism_report.pdf", mimetype="application/pdf")

if __name__ == "__main__":
    app.run(debug=True, port=5000)
